--drop TABLE photos;


CREATE TABLE photos (
 id NUMBER GENERATED BY DEFAULT AS identity,
 uuid VARCHAR2(255),
 creation_date DATE,
 date_added DATE,
 filename VARCHAR(255),
 exiftool CLOB CHECK (exiftool is JSON),
 photojson CLOB check (photojson is JSON),
 location VARCHAR(100),
 make VARCHAR(64),
 model VARCHAR(64)
);


--truncate table photos;

select count(*) from photos;

select json_serialize(photojson) as exif from photos p;

select json_serialize(p.exiftool."EXIF:FocalLength") from photos p;




select count(p.exiftool."EXIF:Make") from photos p where p.exiftool."EXIF:Make" = 'FUJIFILM';


select distinct p.exiftool."EXIF:Make" from photos p where p.exiftool."EXIF:Make" is not NULL;


select * from photos order by creation_date ASC;



select * from photos order by date_added desc;


delete from photos where filename = '20210509_IMG_0165.jpg';